excuteSql:
  allowOrigin: 1
  querySql: SELECT PLSQL FROM META836 WHERE GUID = ?
  charset: gbk
  columnTypeName: BYTEA
  successMessage: 操作成功！-  for postgresql v1.0

server:
  port: 8080

spring:
  application:
    name: AICoder for PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/DB_TEST1
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    time: 2018年06月04日 16:06:05
  describe: AICoder for PostgreSQL
  home: /
  author: Claude
  licensed: MIT Licensed

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: ${spring.application.name}
    health-check-url-path: acutator/info
  client:
    healthcheck:
      enable: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
